#!/bin/bash
# debian_test_build <path to recording>
# script to build a test version of markad in /tmp
# code based on development branch V03
# no installation will be done !

rm -f -r /tmp/vdr-plugin-markad
sudo apt-get install build-essential git pkg-config vdr-dev libavcodec-dev libavformat-dev libavfilter-dev libswresample-dev

cd /tmp
sudo git clone -b V03 https://github.com/kfb77/vdr-plugin-markad

cd vdr-plugin-markad
sudo make all

cd command
sudo ./markad --loglevel=3 --log2rec --pts --fulldecode --threads=1 --logocachedir=/tmp nice "$1"
