#!/bin/bash
# extract all logo sizes from markad.log

VIDEO1="/srv/vdr/video/Archiv_3"
VIDEO2="/srv/vdr/video/Archiv_4"
VIDEO3="/srv/vdr/video/Series"

grep -r "INFO:  processed time" --include "markad.log" $VIDEO1 $VIDEO2 $VIDEO3 | awk -F  " " '{printf "%s:%s\n", $1, $9}' | awk -F  ":" '{printf "%s %s %s\n", $1, $3, $4}' | awk '{printf "%3dmin %3ds %s\n", $2, $3, $1}'  | sort --numeric-sort -k1,1 -k2,2
