#!/bin/bash
# extract all logo sizes from markad.log

VIDEO="/srv/vdr/video"

if [ "$1" == '-v' ]; then
	grep -r "INFO:  processed time" --include "markad.log" $VIDEO | awk -F  " " '{printf "%s:%s\n", $1, $9}' | awk -F  ":" '{printf "%s %s %s\n", $1, $3, $4}' | awk '{printf "%3dmin %3ds %s\n", $2, $3, $1}'  | sort --numeric-sort -k1,1 -k2,2
else
	grep -r "INFO:  processed time" --include "markad.log" $VIDEO | awk -F  " " '{printf "%s:%s\n", $1, $9}' | awk -F  ":" '{printf "%s %s %s\n", $1, $3, $4}' | awk '{printf "%3dmin %3ds %s\n", $2, $3, $1}' | awk '{ sum += $1*60+$2; n++ } END { if (n > 0) printf "average time for logo extraction: %fs from %d recordings\n", sum/n, n }'
fi
