#!/usr/bin/env python3

# remove debug pictures
for filename in glob.glob(self.ConvertPath("/media/Video/VDR/Archiv_1/Filme/Ziemlich_beste_Freunde-Spielfilm_Frankreich_2011_(Intouchables)/2024-03-29.21.42.1-5.rec") + "/F__*.pgm"):
#    os.remove(filename)
     print(filename)

