.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for markad
.\" 
.\" Copyright (C) 2012 Jochen Dolze
.\" 
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the
.\" VDR distribution.
.\" 
.\" $Id: markad.1 1.0 2012/05/25 22:33:34 martinkg Exp $
.\" 
.TH "markad" "1" "25 September 2024" "24.2.0" "A program for the Video Disk Recorder"
.SH "NAME"
MarkAd \- marks advertisements in VDR recordings.
.SH "SYNOPSIS"
.B markad
[options]
.SH "DESCRIPTION"
.B MarkAd
marks advertisements in VDR recordings.
.SH "OPTIONS"
.TP 
Usage: markad [options] <cmd> <recording>
.TP 

.BI \-b\ ,\ \-\-background
\fImarkad\fR runs as a background process;
this will be automatically set if called with "after"
.TP 

.BI \-l\ ,\ \-\-logocachedir
directory where predefined logos were stored, default \fI/var/lib/markad\fR
.RS
Note: Channels sometimes change their logo. If logos kept in the cache are out of date, this will result in bad mark results.
.RE
.TP 

.BI \-\-autologo= <option>
<option>   0 = use logo only from logo cache directory
           1 = extract logo from recording, if fails use logo from logo cache
           2 = use logo from logo cache directory, if missing extract logo from recording (default)
.RS
If no suitable logo file is found, markad will try to find the logo in the video and store the result in the recording directory.
.RE
.TP 

.BI \-\-fulldecode
decode all video frame types
use it only on powerful CPUs, it will double overall run time
.TP

.BI \-\-cut
cut video based on marks and store it in the recording directory
there are no splits of the target file, make sure your filesystem can handle big files
.TP


.BI \-\-smartencode
this option is only available on command line usage
requires --cut
re-encode only short before and short after cut position
.TP

.BI \-\-fullencode=<streams>
this option is only available for command line usage
requires --cut
full re-encode video generated by --cut
use it only on powerful CPUs, it will double overall run time
<streams>  all  = keep all video and audio streams of the recording
           best = only encode best video and best audio stream, drop rest
.TP

.BI \-p\ ,\ \-\-priority= <priority>
software priority of markad when running in background
.RS
<priority>  from \-20...19, default 19
.RE
.TP 

.BI \-r\ ,\ \-\-ioprio= <class>[,<level>]
I/O priority of markad when running in background
.RS
<class>     1 = realtime,   <level> from 0..7, default 4
            2 = besteffort, <level> from 0..7, default 4
            3 = idle (default)
.RE
.RS
Make sure your I/O scheduler supports scheduling priorities and classes (e.g. BFQ or CFQ).
.RE
.TP 

.BI \-v\ ,\ \-\-verbose
increments loglevel by one, can be given multiple times
.TP 

.BI \-B\ ,\ \-\-backupmarks
make a backup of existing marks
.TP 

.BI \-L\ ,\ \-\-extractlogo= <direction>[,width[,height]]
extracts logo to recording directory as pgm files (must be renamed)
.RS
<direction>  0 = top left,    1 = top right
             2 = bottom left, 3 = bottom right
             [width]  range from 50 to 480, default 192 (SD) / 288 (HD)
             [height] range from 20 to 250, default 100 (SD) / 180 (HD)
.RE
.TP 

.BI \-O\ ,\ \-\-OSD
markad sends an OSD message for start and end
.TP 

.BI \-R\ ,\ \-\-log2rec
write log files into recording directory
.TP 

.BI \-T\ ,\ \-\-threads= <number>
number of threads used for decoding, max. 16
(default is the number of CPUs)
.TP 

.BI \-V\ ,\ \-\-version
print version info and exit
.TP 

.BI \-\-loglevel= <level>
sets log level to the specified value
.RS
<level>      1 = error
             2 = info
             3 = debug
             4 = trace
.RE
.TP 

.BI \-\-markfile= <markfilename>
set a different marks filename
.TP 

.BI \-\-nopid
disables creation of \fImarkad.pid\fR file in the recording directory
.TP 

.BI \fB\-\-online[=1|2] 
.RS
only used by markad plugin internal call, do not use it for command line start
.RE
.RS
default is 1
.RE
.RS
start markad immediately when called with "before" as cmd
.RE
.RS
If online is 1, markad starts online for live recordings
only, online=2 starts markad online for every recording.
Live recordings are identified by having a '@' in the
filename, so the entry 'Mark instant recording' in the menu
\fISetup\fR > \fIRecording\fR of the VDR should be set to 'yes'.
.RE
.TP 
.BI \-\-svdrphost= "\fR<ip/hostname> " "\fR(default is 127.0.0.1)"
IP or hostname of a remote VDR for OSD messages
.TP

.BI \-\-ac3reencode
re-encode AC3 stream to fix low audio level of cut video on same devices
requires --cut
use only if really needed, as this consumes significant CPU resources
.RS
.RE
.TP 

.BI \-\-hwaccel= <hardware_acceleration_methode>
use hardware acceleration for decoding
all methods supported by FFmpeg (ffmpeg -hide_banner -hwaccels)
e.g.: vaapi, vdpau, vulkan, cuda ...
.TP

.BI \-\-perftest
run decoder performance test and compare software and hardware decoder
.TP

.BI \-\-vps
use VPS events from markad.vps to optimize start and stop marks
.TP

.BI \-\-svdrpport= \fR<port>\fR  "  ( default is 6419 ) "
 port of a remote VDR for OSD messages
.TP
\fB<cmd>\fR one of:
.RE
.RS
\-            dummy parameter if called directly
.RE
.RS
nice         runs markad directly and with nice(19)
.RE
.RS
after        markad started by VDR after the recording is complete
             only used by markad plugin internal call, do not use it for command line start
.RE
.RS
before       markad started by VDR before the recording is complete, only valid together with --online
             only used by markad plugin internal call, do not use it for command line start
.RE
.RS
edited       markad started by VDR in edit function and exits immediately
             only used by markad plugin internal call, do not use it for command line start
.RE
<record>     is the name of the directory where the recording is stored
.SH "EXIT STATUS"
.TP
.B 0
Successful program execution
.TP
.B 1
An non-recoverable error has been detected, markad has given up. See stderr, syslog or log file in the recording directory for more information

.SH "AUTHOR"
Written by Jochen Dolze <vdr@dolze.de>
.SH "REPORTING BUGS"
Report bugs to https://github.com/kfb77/vdr\-plugin\-markad/issues
.SH "COPYRIGHT"
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
See the file COPYING for more information.
