name: build ubuntu-22.04

on:
  push:
    branches:
      - master
      - V03
      - V04
  pull_request:
    branches:
      - master
      - V03
      - V04

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y vdr-dev libavcodec-dev libavformat-dev libavfilter-dev cppcheck
      - name: make all
        run: make all
      - name: make cppcheck
        run: make cppcheck
